language: csharp
dotnet: 3.1
mono: none
solution: ConsoleApp1.sln
install:
  -nuget restore ConsoleApp1.sln
script:
  - msbuild /p:Configuration=Release ConsoleApp1.sln
  - dotnet restore
  - dotnet test
